import { defineType, defineField } from "sanity";

export default defineType({
  name: "siteSettings",
  title: "Site Settings",
  type: "document",
  icon: () => "⚙️",
  fieldsets: [
    { name: "store", title: "Store Details" },
    { name: "hero", title: "Homepage Hero", options: { collapsible: true, collapsed: false } },
    { name: "shipping", title: "Shipping & Delivery", options: { collapsible: true, collapsed: true } },
    { name: "payments", title: "Payments", options: { collapsible: true, collapsed: true } },
  ],
  fields: [
    defineField({
      name: "storeName",
      title: "Store Name",
      type: "string",
      group: undefined,
      fieldset: "store",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      fieldset: "store",
    }),
    defineField({
      name: "logo",
      title: "Logo",
      type: "image",
      fieldset: "store",
    }),
    defineField({
      name: "phone",
      title: "Phone",
      type: "string",
      fieldset: "store",
    }),
    defineField({
      name: "whatsapp",
      title: "WhatsApp Number",
      description: "Format: 9779812345678",
      type: "string",
      fieldset: "store",
    }),
    defineField({
      name: "email",
      title: "Email",
      type: "string",
      fieldset: "store",
    }),
    defineField({
      name: "address",
      title: "Address",
      type: "text",
      rows: 2,
      fieldset: "store",
    }),
    defineField({
      name: "facebook",
      title: "Facebook URL",
      type: "url",
      fieldset: "store",
    }),
    defineField({
      name: "instagram",
      title: "Instagram URL",
      type: "url",
      fieldset: "store",
    }),
    defineField({
      name: "tiktok",
      title: "TikTok URL",
      type: "url",
      fieldset: "store",
    }),
    defineField({
      name: "announcement",
      title: "Announcement Bar Text",
      type: "string",
      fieldset: "store",
    }),
    defineField({
      name: "heroTitle",
      title: "Hero Title",
      type: "string",
      fieldset: "hero",
    }),
    defineField({
      name: "heroSubtitle",
      title: "Hero Subtitle",
      type: "text",
      rows: 2,
      fieldset: "hero",
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      options: { hotspot: true },
      fieldset: "hero",
    }),
    defineField({
      name: "featuredHeading",
      title: "Featured Products Heading",
      type: "string",
      fieldset: "hero",
    }),
    defineField({
      name: "deliveryFee",
      title: "Standard Delivery Fee (NPR)",
      type: "number",
      initialValue: 100,
      fieldset: "shipping",
    }),
    defineField({
      name: "freeShippingOver",
      title: "Free Shipping Above (NPR)",
      description: "Orders over this amount get free delivery. Leave empty to disable.",
      type: "number",
      fieldset: "shipping",
    }),
    defineField({
      name: "extraDeliveryNote",
      title: "Delivery Note",
      type: "string",
      fieldset: "shipping",
    }),
    defineField({
      name: "codEnabled",
      title: "Enable Cash on Delivery",
      type: "boolean",
      initialValue: true,
      fieldset: "payments",
    }),
    defineField({
      name: "esewaEnabled",
      title: "Enable eSewa",
      type: "boolean",
      initialValue: true,
      fieldset: "payments",
    }),
    defineField({
      name: "khaltiEnabled",
      title: "Enable Khalti",
      type: "boolean",
      initialValue: true,
      fieldset: "payments",
    }),
    defineField({
      name: "footerText",
      title: "Footer Text",
      type: "string",
      fieldset: "store",
    }),
  ],
  preview: {
    select: { title: "storeName", subtitle: "tagline", media: "logo" },
  },
});